export const Routes = {
  Root: '/',
  Welcome: '/',
  Home: '/home',
  Blogs: '/blogs',
  BlogDetail: '/blogs/:slug',
  Feedback: '/feedback',
  Usage: '/usage',
  Datasets: '/datasets',
  DatasetDetail: '/datasets/:id',
  DatasetParseConfig: '/datasets/:id/parse-config',
  Chats: '/chats',
  ChatDetail: '/chats/:id',
  Settings: '/settings',
  LLMPage: '/settings/llm-config',
  ProfilePage: '/settings/profile',
  AdminPage: '/settings/admin',
  AdminRoot: '/admin',
  AdminUsers: '/admin/users',
  AdminBlogs: '/admin/blogs',
  AdminModels: '/admin/models',
  AdminLogs: '/admin/logs',
  AdminBlogEdit: '/admin/blogs/edit/:id',
  CreatorRoot: '/creator',
  CreatorBlogs: '/creator/blogs',
  CreatorBlogEdit: '/creator/blogs/edit/:id',
} as const;
