export const Routes = {
  Root: '/',
  Welcome: '/',
  Home: '/home',
  Blogs: '/blogs',
  BlogDetail: '/blogs/:slug',
  Feedback: '/feedback',
  Usage: '/usage',
  Datasets: '/datasets',
  DatasetDetail: '/datasets/:id',
  Chats: '/chats',
  ChatDetail: '/chats/:id',
  Files: '/files',
  Settings: '/settings',
  LLMPage: '/settings/llm-config',
  ProfilePage: '/settings/profile',
  CreatorRoot: '/creator',
  CreatorBlogs: '/creator/blogs',
  CreatorBlogEdit: '/creator/blogs/edit/:id',
} as const;
